[build]
  publish = "_site"
  command = "npm run build"
  
 [[redirects]]
  from = "/discord"
  to = "https://discord.gg/jWbPshhVAv"
  status = 302
  
 [[redirects]]
  from = "/twitch"
  to = "https://www.twitch.tv/tofudimsum"
  status = 302
  
 [[redirects]]
  from = "/donate"
  to = "https://streamlabs.com/tofudimsum/v2"
  status = 302
